### ISSUE TITLE
Nessus 10 Integration [FR]

### ISSUE THREAD

**Issue by phmazzoni** [DSecureMe/vmc#59]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Is it possible to integrate it with Nessus Professional 10?

**Describe alternatives you've considered**
Use the Nessus 8 integration an test it.

**Additional context**
Add any other context or screenshots about the fea

**Comment by mwalkowski** [comment]
Hi @phmazzoni ,

Thank you for your FR but at the moment we don't have free resources to do additional implementations. But feel free to create PR.
