### ISSUE TITLE
Installing Issue 

### ISSUE THREAD

**Issue by danhgh2** [DSecureMe/vmc#61]
Dear Dsecureme
I found your tool very interesting and useful so i tried to install using docker. But I can't run it according to your instructions. I have tried many different ways and it still doesn't work. It's a lot of errors when compose. I think your tool has some problem in some config file. When I run it quits immediately
Hope you fix this issue soon

**Comment by mwalkowski** [comment]
Hi @danhgh2, Can you provide more information and include the errors you get?

**Comment by danhgh2** [comment]
Dear Walkowski
Here is my problem. I tried many ways to install it but it's still not
working.
Can you give me more details step by step about how to install and use it
[image: Screenshot (721).png]
[image: Screenshot 2023-06-05 191744.png]

Vào Th 2, 5 thg 6, 2023 vào lúc 17:05 Michał Walkowski <
***@***.***> đã viết:

**Comment by mwalkowski** [comment]
Screenshots are missing in your answer.

Have you tried following the instructions described [here](https://github.com/DSecureMe/vmc-demo)?

**Comment by danhgh2** [comment]
I followed the instructions properly but still can't get it to run. i have
successfully accessed ports 9200, 5601, 9000, 5672 as required but VMC
still cannot connect. I think it's configuration problem. Can you give me
detailed step-by-step instructions on how to do it, with pictures as
possible. I've been trying for over a week but still no success

Vào 19:36, T.2, 5 Th6, 2023 Michał Walkowski ***@***.***> đã
viết:

**Comment by danhgh2** [comment]
Or can I chat with anyone of the developer. Can you guide me in more detail

Vào 21:31, T.2, 5 Th6, 2023 Phương Danh ***@***.***> đã viết:

**Comment by mwalkowski** [comment]
Without any logs or screenshots, I'm unable to help you.

**Comment by danhgh2** [comment]
First pic is i tried to run the vmc image and it exited immediately, i
can't see any log.
Second pic is i tried to run the compose up cmd and it's the log.
How can i chat with your team in a more convenient way

Vào 21:36, T.2, 5 Th6, 2023 Michał Walkowski ***@***.***> đã
viết:

**Comment by mwalkowski** [comment]
Please visit this thread via the github page to verify that no screenshots have been attached to your answer :)

**Comment by danhgh2** [comment]
Oh sorry, I reply you by email but I don't understand why it's not showing the image. Here's my screenshot 
![Screenshot 2023-06-05 191744](https://github.com/DSecureMe/vmc/assets/92416927/deae8d13-5b9f-4b9c-9bba-acbf6d86239e)
![Screenshot (721)](https://github.com/DSecureMe/vmc/assets/92416927/dc975a8c-f5cd-474f-8b78-c2a59c923ad7)

**Comment by danhgh2** [comment]
Can you explain step by step how can i install it by docker

**Comment by danhgh2** [comment]
Can you see my sceenshot

**Comment by mwalkowski** [comment]
The screenshots you provided don't show anything. Please post the full runtime log.

The minimum resources required to run the application are described [here](https://github.com/DSecureMe/vmc-docs).

It may take up to several minutes for the whole thing to get up, depending on how many resources (RAM & CPU) you have added to your virtual machine.

**Comment by danhgh2** [comment]
The log runs continuously I don't know what to do to send full-time. About running the image it doesn't show any log but exited immediately

**Comment by danhgh2** [comment]
Can you guide me from start to finish?

**Comment by mwalkowski** [comment]
Sorry, but everything works on my side. I did the same steps that are provided in [Readme](https://github.com/DSecureMe/vmc-demo).
Without proper documented logs and steps provided by you, I can't help you.

Please provide detailed reproduction steps, or if you don't know how to create the correct issue/bug description please read for example this article https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f
