### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by tuannonh** [DSecureMe/vmc#62]
**Describe the bug**
I installing elasticsearch on port 9200, but when i install vmc-demo i can't connect port 9200 although i can access localhost:9200

**To Reproduce**
1. Install elasticsearch
2. Install rabbitmq
3. Install postgresql
4. Install nginx
5. Install vmc docker
6. Install vmc demo

**Expected behavior**
When i install vmc-demo i can't connect to eleasticsearch althought i install completed anh i succesfully access to localhost:92000

**Screenshots**
![image](https://github.com/DSecureMe/vmc/assets/65121914/6909ba77-93ab-426b-b5a6-1e6cfd0004eb)
![image](https://github.com/DSecureMe/vmc/assets/65121914/5ef1da9a-cdf5-4b2b-80e0-a31323b0a898)

**Additional context**

**Comment by mwalkowski** [comment]
Hi @tuannonh,

If you are using vmc-demo, you don't need to install any other things, just the docker and docker-compose plugin.
If you installed the other components yourself, maybe those that are configured in docker-compose are not able to start and VMC can't connect to them. Try disabling/uninstalling unnecessary components.

**Comment by tuannonh** [comment]
Ok, I will try

**Comment by tuannonh** [comment]
![image](https://github.com/DSecureMe/vmc/assets/65121914/ea05e578-fcb7-4cc2-90ac-05cf5da2c369)

**Comment by tuannonh** [comment]
More error

**Comment by mwalkowski** [comment]
it's ok, now you need to wait for kibana will be ready, then in a separate console call ` make demodata`

**Comment by tuannonh** [comment]
Do I need to install kibana?

**Comment by tuannonh** [comment]
I waited 10 minutes and it's still the same

**Comment by mwalkowski** [comment]
You don't need to install Kibana.
You need to check that Kibana is ready on `:5601 `.

**Comment by tuannonh** [comment]
I can access to kibana but I still waited to long to install complete
![image](https://github.com/DSecureMe/vmc/assets/65121914/6db22621-b1da-4480-93fe-1ef3a1809a05)

**Comment by mwalkowski** [comment]
Did you execute `make demodata`?

**Comment by tuannonh** [comment]
Another console ?

**Comment by tuannonh** [comment]
![image](https://github.com/DSecureMe/vmc/assets/65121914/5292c3d4-8004-4a7f-9a6f-5a4adb43fc74)
Error timeout

**Comment by mwalkowski** [comment]
the entire `demodata` process went through without problems?

**Comment by tuannonh** [comment]
I ran make demodata for a while then stopped working until now

**Comment by tuannonh** [comment]
And continue timeout

**Comment by tuannonh** [comment]
Hello, i completed install vmc-demo, but when i access port 9200, the port i unavailable, and kibana don't connect to elasticsearch, what can I do?
![image](https://github.com/DSecureMe/vmc/assets/65121914/f20f76fd-e902-4ba5-b71a-1607ddf62210)
![image](https://github.com/DSecureMe/vmc/assets/65121914/72cb6eaa-7e66-43d7-ab53-35bbd021879a)
![image](https://github.com/DSecureMe/vmc/assets/65121914/f720e0a2-8222-49e3-9e57-b455eee87b3f)

**Comment by tuannonh** [comment]
![image](https://github.com/DSecureMe/vmc/assets/65121914/f214c558-1b16-427f-9976-d9b3ba90e7a1)

**Comment by mwalkowski** [comment]
logs?
Who the hell told you, that screenshots are good for problem reporting?

Before vmc start please try:
`sudo sysctl -w vm.max_map_count=262144`

**Comment by tuannonh** [comment]
and then execute make demodata?

**Comment by mwalkowski** [comment]
1. `sudo sysctl -w vm.max_map_count=262144`
2. `make up`
3.  `make demodata`

**Comment by tuannonh** [comment]
Port 9200 continue unable to connect

**Comment by tuannonh** [comment]
When I execute make demodata I can't access port 9200

**Comment by mwalkowski** [comment]
please provide the detailed full log from `make up`, also please provide results from docker ps command and your VM capacity: total RAM and vCPU.

**Comment by tuannonh** [comment]
![image](https://github.com/DSecureMe/vmc/assets/65121914/4e28130d-9bff-4a4a-a18d-baa240f34591)
![image](https://github.com/DSecureMe/vmc/assets/65121914/b36a4738-bfad-403e-9db4-37fd83a0c37b)

**Comment by tuannonh** [comment]
![image](https://github.com/DSecureMe/vmc/assets/65121914/76e8a53d-7a7c-42c7-8fe4-7d91c5cc3c14)

**Comment by mwalkowski** [comment]
you don't have enough RAM and vCPU to get everything running, please read [requirements](https://github.com/DSecureMe/vmc-docs). That is the main problem why elasticsearch on 9200 is not running.

Also, I asked to provide full log from `makeup`, not a screenshot....
